# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji

# Site settings
url: 'https://osuked.com'
baseurl: ''
title: 'OSUKED'
description: 'Open Source UK Energy Data'
permalink: pretty
logo: "https://raw.githubusercontent.com/AyrtonB/OSUKED-Site/master/uploads/logo.svg"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: OSUKED
  url: /

# Footer nav
navigation_footer:
- title: ^
  url: "#top"
